"""add_reminder_settings_table

Revision ID: 191112f95d1c
Revises: dc881042f137
Create Date: 2026-01-16 18:34:10.707091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191112f95d1c'
down_revision = 'dc881042f137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('business_id', sa.UUID(), nullable=False),
        sa.Column('auto_send_enabled', sa.Boolean(), nullable=False),
        sa.Column('auto_approve_stage_1', sa.Boolean(), nullable=False),
        sa.Column('stage_1_days', sa.Integer(), nullable=False),
        sa.Column('stage_2_days', sa.Integer(), nullable=False),
        sa.Column('stage_3_days', sa.Integer(), nullable=False),
        sa.Column('stage_4_days', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_settings')
    # ### end Alembic commands ###
