"""add_reminder_enhancements

Revision ID: dc881042f137
Revises: acc9a73c0968
Create Date: 2026-01-15 18:15:55.439461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc881042f137'
down_revision = 'acc9a73c0968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum types
    reminderstatus_enum = sa.Enum('PENDING', 'APPROVED', 'SCHEDULED', 'SENT', 'FAILED', name='reminderstatus')
    reminderstatus_enum.create(op.get_bind(), checkfirst=True)

    # Update tone enum to add new values
    op.execute("ALTER TYPE remindertone ADD VALUE IF NOT EXISTS 'professional'")
    op.execute("ALTER TYPE remindertone ADD VALUE IF NOT EXISTS 'formal'")

    # Add new columns
    op.add_column('clients', sa.Column('relationship_notes', sa.Text(), nullable=True))
    op.add_column('reminder_drafts', sa.Column('escalation_level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('reminder_drafts', sa.Column('subject', sa.String(length=255), nullable=False, server_default='Payment Reminder'))
    op.add_column('reminder_drafts', sa.Column('status', reminderstatus_enum, nullable=False, server_default='PENDING'))
    op.add_column('reminder_drafts', sa.Column('auto_send_at', sa.DateTime(), nullable=True))
    op.add_column('reminder_drafts', sa.Column('delivery_status', sa.String(length=50), nullable=True))

    # Remove server defaults after adding columns
    op.alter_column('reminder_drafts', 'escalation_level', server_default=None)
    op.alter_column('reminder_drafts', 'subject', server_default=None)
    op.alter_column('reminder_drafts', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder_drafts', 'delivery_status')
    op.drop_column('reminder_drafts', 'auto_send_at')
    op.drop_column('reminder_drafts', 'status')
    op.drop_column('reminder_drafts', 'subject')
    op.drop_column('reminder_drafts', 'escalation_level')
    op.drop_column('clients', 'relationship_notes')
    # ### end Alembic commands ###
